version: '2'

services:
  db:
    image: postgres:9.6
    env_file:
      - ./conf/start/docker/postgres.env
    ports:
      - "5432:5432"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    networks:
      default:
        aliases:
          - elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  rabbitmq:
    image: rabbitmq:3
  promsrv:
    build: ./conf/start/docker/prometheus/
    volumes:
      - prometheus_sd:/prometheus_sd
  nginx:
    image: nginx:stable
    ports:
      - "443:443"
    depends_on:
      - promsrv
      - web
    volumes:
      - ./conf/start/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/start/docker/tls:/etc/nginx/tls
      - web_static_root:/zentral_static
  web:
    extends:
      file: docker-compose.common.yml
      service: app
    command: runserver
    depends_on:
      - db
      - elastic
      - rabbitmq
    volumes:
      - web_media_root:/var/zentral
      - web_static_root:/zentral_static
  workers:
    extends:
      file: docker-compose.common.yml
      service: app
    command: runworkers --external-hostname workers --prometheus-sd-file /prometheus_sd/workers.yml
    depends_on:
      - db
      - elastic
      - rabbitmq
    volumes:
      - web_media_root:/var/zentral
      - prometheus_sd:/prometheus_sd

networks:
  default:

volumes:
  elasticsearch_data:
  prometheus_sd:
  web_media_root:
  web_static_root:
